// <auto-generated/>
#nullable enable

using System;
using System.Numerics;
using Exanite.Core.Numerics;

namespace Exanite.Core.Utilities;

public static partial class M
{
    /// <summary>
    /// Component-wise clamps the provided vector to the bounds given by <see cref="min"/> and <see cref="max"/>.
    /// </summary>
    public static void Clamp(ref this Vector4Fixed vector, Vector4Fixed min, Vector4Fixed max)
    {
        vector.X = Clamp(vector.X, min.X, max.X);
        vector.Y = Clamp(vector.Y, min.Y, max.Y);
        vector.Z = Clamp(vector.Z, min.Z, max.Z);
        vector.W = Clamp(vector.W, min.W, max.W);
    }
}
