// <auto-generated/>
#nullable enable

using System;
using System.Numerics;
using Exanite.Core.Numerics;

namespace Exanite.Core.Utilities;

public static partial class M
{
    /// <summary>
    /// Converts a <see cref="Vector2Int"/> to a <see cref="Vector3Int"/> by adding components.
    /// </summary>
    public static Vector3Int Xy0(this Vector2Int value)
    {
        return new Vector3Int(value.X, value.Y, 0);
    }

    /// <summary>
    /// Converts a <see cref="Vector2Int"/> to a <see cref="Vector3Int"/> by adding components.
    /// </summary>
    public static Vector3Int Xy1(this Vector2Int value)
    {
        return new Vector3Int(value.X, value.Y, 1);
    }

    /// <summary>
    /// Converts a <see cref="Vector2Int"/> to a <see cref="Vector4Int"/> by adding components.
    /// </summary>
    public static Vector4Int Xy00(this Vector2Int value)
    {
        return new Vector4Int(value.X, value.Y, 0, 0);
    }

    /// <summary>
    /// Converts a <see cref="Vector2Int"/> to a <see cref="Vector4Int"/> by adding components.
    /// </summary>
    public static Vector4Int Xy01(this Vector2Int value)
    {
        return new Vector4Int(value.X, value.Y, 0, 1);
    }

    /// <summary>
    /// Converts a <see cref="Vector2Int"/> to a <see cref="Vector4Int"/> by adding components.
    /// </summary>
    public static Vector4Int Xy10(this Vector2Int value)
    {
        return new Vector4Int(value.X, value.Y, 1, 0);
    }

    /// <summary>
    /// Converts a <see cref="Vector2Int"/> to a <see cref="Vector4Int"/> by adding components.
    /// </summary>
    public static Vector4Int Xy11(this Vector2Int value)
    {
        return new Vector4Int(value.X, value.Y, 1, 1);
    }

    /// <summary>
    /// Converts a <see cref="Vector3Int"/> to a <see cref="Vector2Int"/> by dropping components.
    /// </summary>
    public static Vector2Int Xy(this Vector3Int value)
    {
        return new Vector2Int(value.X, value.Y);
    }

    /// <summary>
    /// Converts a <see cref="Vector3Int"/> to a <see cref="Vector4Int"/> by adding components.
    /// </summary>
    public static Vector4Int Xyz0(this Vector3Int value)
    {
        return new Vector4Int(value.X, value.Y, value.Z, 0);
    }

    /// <summary>
    /// Converts a <see cref="Vector3Int"/> to a <see cref="Vector4Int"/> by adding components.
    /// </summary>
    public static Vector4Int Xyz1(this Vector3Int value)
    {
        return new Vector4Int(value.X, value.Y, value.Z, 1);
    }

    /// <summary>
    /// Converts a <see cref="Vector4Int"/> to a <see cref="Vector2Int"/> by dropping components.
    /// </summary>
    public static Vector2Int Xy(this Vector4Int value)
    {
        return new Vector2Int(value.X, value.Y);
    }

    /// <summary>
    /// Converts a <see cref="Vector4Int"/> to a <see cref="Vector3Int"/> by dropping components.
    /// </summary>
    public static Vector3Int Xyz(this Vector4Int value)
    {
        return new Vector3Int(value.X, value.Y, value.Z);
    }
}
