// <auto-generated/>
#nullable enable

using System;
using System.Numerics;
using Exanite.Core.Numerics;

namespace Exanite.Core.Utilities;

public static partial class M
{
    /// <summary>
    /// Interpolates from one vector to another by <see cref="t"/>.
    /// <see cref="t"/> will be clamped in the range [0, 1]
    /// </summary>
    public static Vector2Fixed Lerp(Vector2Fixed from, Vector2Fixed to, Fixed t)
    {
        t = Clamp01(t);
        return from + (to - from) * t;
    }

    /// <summary>
    /// Interpolates from one vector to another by <see cref="t"/>.
    /// </summary>
    public static Vector2Fixed LerpUnclamped(Vector2Fixed from, Vector2Fixed to, Fixed t)
    {
        return from + (to - from) * t;
    }

    /// <summary>
    /// Component-wise clamps the provided vector to the bounds given by <see cref="min"/> and <see cref="max"/>.
    /// </summary>
    public static void Clamp(ref this Vector2Fixed vector, Vector2Fixed min, Vector2Fixed max)
    {
        vector.X = Clamp(vector.X, min.X, max.X);
        vector.Y = Clamp(vector.Y, min.Y, max.Y);
    }
}
