// <auto-generated/>
#nullable enable

using System;
using System.Numerics;
using Exanite.Core.Numerics;

namespace Exanite.Core.Utilities;

public static partial class M
{
    /// <summary>
    /// Converts a <see cref="Vector2"/> to a <see cref="Vector3"/> by adding components.
    /// </summary>
    public static Vector3 Xy0(this Vector2 value)
    {
        return new Vector3(value.X, value.Y, 0);
    }

    /// <summary>
    /// Converts a <see cref="Vector2"/> to a <see cref="Vector3"/> by adding components.
    /// </summary>
    public static Vector3 Xy1(this Vector2 value)
    {
        return new Vector3(value.X, value.Y, 1);
    }

    /// <summary>
    /// Converts a <see cref="Vector2"/> to a <see cref="Vector4"/> by adding components.
    /// </summary>
    public static Vector4 Xy00(this Vector2 value)
    {
        return new Vector4(value.X, value.Y, 0, 0);
    }

    /// <summary>
    /// Converts a <see cref="Vector2"/> to a <see cref="Vector4"/> by adding components.
    /// </summary>
    public static Vector4 Xy01(this Vector2 value)
    {
        return new Vector4(value.X, value.Y, 0, 1);
    }

    /// <summary>
    /// Converts a <see cref="Vector2"/> to a <see cref="Vector4"/> by adding components.
    /// </summary>
    public static Vector4 Xy10(this Vector2 value)
    {
        return new Vector4(value.X, value.Y, 1, 0);
    }

    /// <summary>
    /// Converts a <see cref="Vector2"/> to a <see cref="Vector4"/> by adding components.
    /// </summary>
    public static Vector4 Xy11(this Vector2 value)
    {
        return new Vector4(value.X, value.Y, 1, 1);
    }

    /// <summary>
    /// Converts a <see cref="Vector3"/> to a <see cref="Vector2"/> by dropping components.
    /// </summary>
    public static Vector2 Xy(this Vector3 value)
    {
        return new Vector2(value.X, value.Y);
    }

    /// <summary>
    /// Converts a <see cref="Vector3"/> to a <see cref="Vector4"/> by adding components.
    /// </summary>
    public static Vector4 Xyz0(this Vector3 value)
    {
        return new Vector4(value.X, value.Y, value.Z, 0);
    }

    /// <summary>
    /// Converts a <see cref="Vector3"/> to a <see cref="Vector4"/> by adding components.
    /// </summary>
    public static Vector4 Xyz1(this Vector3 value)
    {
        return new Vector4(value.X, value.Y, value.Z, 1);
    }

    /// <summary>
    /// Converts a <see cref="Vector4"/> to a <see cref="Vector2"/> by dropping components.
    /// </summary>
    public static Vector2 Xy(this Vector4 value)
    {
        return new Vector2(value.X, value.Y);
    }

    /// <summary>
    /// Converts a <see cref="Vector4"/> to a <see cref="Vector3"/> by dropping components.
    /// </summary>
    public static Vector3 Xyz(this Vector4 value)
    {
        return new Vector3(value.X, value.Y, value.Z);
    }
}
