// <auto-generated/>
#nullable enable

using System;
using System.Numerics;
using Exanite.Core.Numerics;

namespace Exanite.Core.Utilities;

public static partial class M
{
    /// <summary>
    /// Interpolates from one vector to another by <see cref="t"/>.
    /// <see cref="t"/> will be clamped in the range [0, 1]
    /// </summary>
    public static Vector4 Lerp(Vector4 from, Vector4 to, float t)
    {
        t = Clamp01(t);
        return from + (to - from) * t;
    }

    /// <summary>
    /// Interpolates from one vector to another by <see cref="t"/>.
    /// </summary>
    public static Vector4 LerpUnclamped(Vector4 from, Vector4 to, float t)
    {
        return from + (to - from) * t;
    }

    /// <inheritdoc cref="SmoothDamp{T}"/>
    public static Vector4 SmoothDamp(Vector4 current, Vector4 target, float smoothTime, float deltaTime, ref Vector4 currentVelocity)
    {
        var result = new Vector4(SmoothDamp(current.X, target.X, smoothTime, deltaTime, ref currentVelocity.X, float.PositiveInfinity), SmoothDamp(current.Y, target.Y, smoothTime, deltaTime, ref currentVelocity.Y, float.PositiveInfinity), SmoothDamp(current.Z, target.Z, smoothTime, deltaTime, ref currentVelocity.Z, float.PositiveInfinity), SmoothDamp(current.W, target.W, smoothTime, deltaTime, ref currentVelocity.W, float.PositiveInfinity));
        currentVelocity = ClampMagnitude(currentVelocity, float.PositiveInfinity);

        return result;
    }

    /// <inheritdoc cref="SmoothDamp{T}"/>
    public static Vector4 SmoothDamp(Vector4 current, Vector4 target, float smoothTime, float deltaTime, ref Vector4 currentVelocity, float maxSpeed)
    {
        var result = new Vector4(SmoothDamp(current.X, target.X, smoothTime, deltaTime, ref currentVelocity.X, maxSpeed), SmoothDamp(current.Y, target.Y, smoothTime, deltaTime, ref currentVelocity.Y, maxSpeed), SmoothDamp(current.Z, target.Z, smoothTime, deltaTime, ref currentVelocity.Z, maxSpeed), SmoothDamp(current.W, target.W, smoothTime, deltaTime, ref currentVelocity.W, maxSpeed));
        currentVelocity = ClampMagnitude(currentVelocity, maxSpeed);

        return result;
    }

    /// <summary>
    /// Clamps the length of the provided vector to between [0, maxLength].
    /// </summary>
    public static Vector4 ClampMagnitude(Vector4 value, float maxLength)
    {
        return ClampMagnitude(value, 0, maxLength);
    }

    /// <summary>
    /// Clamps the length of the provided vector to between [minLength, maxLength].
    /// If a zero vector is provided, then the result is a zero vector.
    /// </summary>
    public static Vector4 ClampMagnitude(Vector4 value, float minLength, float maxLength)
    {
        return value.AsNormalizedOrDefault() * Clamp(value.Length(), minLength, maxLength);
    }

    /// <summary>
    /// Returns the normalized version of the provided vector, or returns zero if the provided vector is zero.
    /// </summary>
    public static Vector4 AsNormalizedOrDefault(this Vector4 value)
    {
        return value.AsNormalizedOrDefault(Vector4.Zero);
    }

    /// <summary>
    /// Returns the normalized version of the provided vector, or returns the specified default value if the provided vector is zero.
    /// </summary>
    public static Vector4 AsNormalizedOrDefault(this Vector4 value, Vector4 defaultValue)
    {
        return value == Vector4.Zero ? defaultValue : Vector4.Normalize(value);
    }

    /// <summary>
    /// Checks if two vectors are approximately the same value based on the provided <see cref="tolerance"/>.
    /// </summary>
    public static bool ApproximatelyEquals(Vector4 a, Vector4 b)
    {
        return ApproximatelyEquals(a.X, b.X, 0.000001f) && ApproximatelyEquals(a.Y, b.Y, 0.000001f) && ApproximatelyEquals(a.Z, b.Z, 0.000001f) && ApproximatelyEquals(a.W, b.W, 0.000001f);
    }

    /// <summary>
    /// Checks if two vectors are approximately the same value based on the provided <see cref="tolerance"/>.
    /// </summary>
    public static bool ApproximatelyEquals(Vector4 a, Vector4 b, float tolerance)
    {
        return ApproximatelyEquals(a.X, b.X, tolerance) && ApproximatelyEquals(a.Y, b.Y, tolerance) && ApproximatelyEquals(a.Z, b.Z, tolerance) && ApproximatelyEquals(a.W, b.W, tolerance);
    }

    /// <summary>
    /// Component-wise clamps the provided vector to the bounds given by <see cref="min"/> and <see cref="max"/>.
    /// </summary>
    public static void Clamp(ref this Vector4 vector, Vector4 min, Vector4 max)
    {
        vector.X = Clamp(vector.X, min.X, max.X);
        vector.Y = Clamp(vector.Y, min.Y, max.Y);
        vector.Z = Clamp(vector.Z, min.Z, max.Z);
        vector.W = Clamp(vector.W, min.W, max.W);
    }
}
