// <auto-generated/>
#nullable enable

using System;
using System.Numerics;
using Exanite.Core.Numerics;

namespace Exanite.Core.Utilities;

public static partial class M
{
    /// <summary>
    /// Converts a <see cref="Vector2Fixed"/> to a <see cref="Vector3Fixed"/> by adding components.
    /// </summary>
    public static Vector3Fixed Xy0(this Vector2Fixed value)
    {
        return new Vector3Fixed(value.X, value.Y, 0);
    }

    /// <summary>
    /// Converts a <see cref="Vector2Fixed"/> to a <see cref="Vector3Fixed"/> by adding components.
    /// </summary>
    public static Vector3Fixed Xy1(this Vector2Fixed value)
    {
        return new Vector3Fixed(value.X, value.Y, 1);
    }

    /// <summary>
    /// Converts a <see cref="Vector2Fixed"/> to a <see cref="Vector4Fixed"/> by adding components.
    /// </summary>
    public static Vector4Fixed Xy00(this Vector2Fixed value)
    {
        return new Vector4Fixed(value.X, value.Y, 0, 0);
    }

    /// <summary>
    /// Converts a <see cref="Vector2Fixed"/> to a <see cref="Vector4Fixed"/> by adding components.
    /// </summary>
    public static Vector4Fixed Xy01(this Vector2Fixed value)
    {
        return new Vector4Fixed(value.X, value.Y, 0, 1);
    }

    /// <summary>
    /// Converts a <see cref="Vector2Fixed"/> to a <see cref="Vector4Fixed"/> by adding components.
    /// </summary>
    public static Vector4Fixed Xy10(this Vector2Fixed value)
    {
        return new Vector4Fixed(value.X, value.Y, 1, 0);
    }

    /// <summary>
    /// Converts a <see cref="Vector2Fixed"/> to a <see cref="Vector4Fixed"/> by adding components.
    /// </summary>
    public static Vector4Fixed Xy11(this Vector2Fixed value)
    {
        return new Vector4Fixed(value.X, value.Y, 1, 1);
    }

    /// <summary>
    /// Converts a <see cref="Vector3Fixed"/> to a <see cref="Vector2Fixed"/> by dropping components.
    /// </summary>
    public static Vector2Fixed Xy(this Vector3Fixed value)
    {
        return new Vector2Fixed(value.X, value.Y);
    }

    /// <summary>
    /// Converts a <see cref="Vector3Fixed"/> to a <see cref="Vector4Fixed"/> by adding components.
    /// </summary>
    public static Vector4Fixed Xyz0(this Vector3Fixed value)
    {
        return new Vector4Fixed(value.X, value.Y, value.Z, 0);
    }

    /// <summary>
    /// Converts a <see cref="Vector3Fixed"/> to a <see cref="Vector4Fixed"/> by adding components.
    /// </summary>
    public static Vector4Fixed Xyz1(this Vector3Fixed value)
    {
        return new Vector4Fixed(value.X, value.Y, value.Z, 1);
    }

    /// <summary>
    /// Converts a <see cref="Vector4Fixed"/> to a <see cref="Vector2Fixed"/> by dropping components.
    /// </summary>
    public static Vector2Fixed Xy(this Vector4Fixed value)
    {
        return new Vector2Fixed(value.X, value.Y);
    }

    /// <summary>
    /// Converts a <see cref="Vector4Fixed"/> to a <see cref="Vector3Fixed"/> by dropping components.
    /// </summary>
    public static Vector3Fixed Xyz(this Vector4Fixed value)
    {
        return new Vector3Fixed(value.X, value.Y, value.Z);
    }
}
