// <auto-generated/>
#nullable enable

using System;
using System.Numerics;
using Exanite.Core.Utilities;

namespace Exanite.Core.Numerics;

public partial record struct Color
{
    // Linear

    public readonly Color Linear => As(ColorType.Linear);

    public static Color FromLinear(Vector3 value)
    {
        return new Color(value.Xyz1(), ColorType.Linear);
    }

    public static Color FromLinear(Vector4 value)
    {
        return new Color(value, ColorType.Linear);
    }

    public static Color FromLinear(float r, float g, float b, float a = 1)
    {
        return new Color(new Vector4(r, g, b, a), ColorType.Linear);
    }

    // Srgb

    public readonly Color Srgb => As(ColorType.Srgb);

    public static Color FromSrgb(Vector3 value)
    {
        return new Color(value.Xyz1(), ColorType.Srgb);
    }

    public static Color FromSrgb(Vector4 value)
    {
        return new Color(value, ColorType.Srgb);
    }

    public static Color FromSrgb(float r, float g, float b, float a = 1)
    {
        return new Color(new Vector4(r, g, b, a), ColorType.Srgb);
    }

    // Hsl

    public readonly Color Hsl => As(ColorType.Hsl);

    public static Color FromHsl(Vector3 value)
    {
        return new Color(value.Xyz1(), ColorType.Hsl);
    }

    public static Color FromHsl(Vector4 value)
    {
        return new Color(value, ColorType.Hsl);
    }

    public static Color FromHsl(float h, float s, float l, float a = 1)
    {
        return new Color(new Vector4(h, s, l, a), ColorType.Hsl);
    }
}
