// <auto-generated/>
#nullable enable

namespace Exanite.Core.Numerics;

public partial struct Fixed
{
    private const int ERaw = 712581;
    private const int PiRaw = 823550;
    private const int PiHalfRaw = 411775;
    private const int PiFourthRaw = 205887;
    private const int PiInverseRaw = 83443;
    private const int TauRaw = 1647099;

    private const int LogETwoRaw = 181704;
    private const int Log10TwoRaw = 78913;

    // Exp2 Taylor series constants (minimax)
    private const int Exp2TermShift = 32;
    private const uint Exp2Term1 = 2977044556;
    private const uint Exp2Term2 = 1031750445;
    private const uint Exp2Term3 = 238469942;
    private const uint Exp2Term4 = 41153905;
    private const uint Exp2Term5 = 6044437;
    private const uint Exp2Term6 = 499247;

    /// <summary>
    /// Q4.60 format.
    /// </summary>
    private const long TauPreciseRaw = 7244019458077126904;
    private const int TauPreciseShift = 60;

    /// <summary>
    /// Q4.60 format.
    /// </summary>
    private const long PiPreciseRaw = 3622009729038557687;
    private const int PiPreciseShift = 60;
}
