// <auto-generated/>
#nullable enable

using System.Collections.Immutable;

namespace Exanite.Core.Numerics;

public partial struct Fixed
{
    public static readonly ImmutableArray<int> DigitsLut = [
        9,
        99,
        999,
        9999,
        99999,
        999999,
        9999999,
        99999999,
        999999999,
        2147483647,
    ];

    public const int SqrtLutBits = 4;
    public static readonly ImmutableArray<int> SqrtLut = [
        92681, 85448, 79681, 74943, 70961, 67552, 64592, 61990,
        59679, 57609, 55740, 54042, 52490, 51065, 49750, 48531,
    ];
}
