// <auto-generated/>
#nullable enable

using System.Collections.Immutable;

namespace Exanite.Core.Numerics;

public partial struct Fixed
{
    public static readonly ImmutableArray<int> DigitsLut = [
        9,
        99,
        999,
        9999,
        99999,
        999999,
        9999999,
        99999999,
        999999999,
        2147483647,
    ];
}
