// <auto-generated/>
#nullable enable

namespace Exanite.Core.Numerics;

public partial struct Fixed
{
    private const long ERaw = 178145;
    private const long PiRaw = 205887;
    private const long PiHalfRaw = 102944;
    private const long PiFourthRaw = 51472;
    private const long PiInverseRaw = 20861;
    private const long TauRaw = 411775;

    private const long LogETwoRaw = 45426;
    private const long Log10TwoRaw = 19728;

    // Exp2 Taylor Series Constants
    private const long Exp2Term1 = 45426;
    private const long Exp2Term2 = 15743;
    private const long Exp2Term3 = 3638;
    private const long Exp2Term4 = 630;

    /// <summary>
    /// Q4.60 format.
    /// </summary>
    private const long TauPreciseRaw = 7244019458077126904;
    private const int TauPreciseShift = 60;

    /// <summary>
    /// Q4.60 format.
    /// </summary>
    private const long PiPreciseRaw = 3622009729038557687;
    private const int PiPreciseShift = 60;
}
