// <auto-generated/>
#nullable enable

namespace Exanite.Core.Numerics;

public partial struct Fixed
{
    /// <summary>
    /// Equal to round(e * 2^16).
    /// </summary>
    private const long ERaw = 178145;

    /// <summary>
    /// Equal to round(pi * 2^16).
    /// </summary>
    private const long PiRaw = 205887;

    /// <summary>
    /// Equal to round(pi * 2^16 / 2).
    /// </summary>
    private const long PiHalfRaw = 102944;

    /// <summary>
    /// Equal to round(pi * 2^16 / 4).
    /// </summary>
    private const long PiFourthRaw = 51472;

    /// <summary>
    /// Equal to round((1 / pi) * 2^16).
    /// </summary>
    private const long PiInverseRaw = 20861;

    /// <summary>
    /// Equal to round(pi * 2^16 * 2).
    /// </summary>
    private const long TauRaw = 411775;

    /// <summary>
    /// Q4.60 format. Equal to round(tau * 2^60).
    /// </summary>
    private const long TauPreciseRaw = 7244019458077126904;
    private const int TauPreciseShift = 60;

    /// <summary>
    /// Q4.60 format. Equal to round(pi * 2^60).
    /// </summary>
    private const long PiPreciseRaw = 3622009729038557687;
    private const int PiPreciseShift = 60;
}
