// <auto-generated/>
#nullable enable

using System.Collections.Immutable;

namespace Exanite.Core.Numerics;

public partial struct Fixed
{
    public static readonly ImmutableArray<int> DigitsLut = [
        9,
        99,
        999,
        9999,
        99999,
        999999,
        9999999,
        99999999,
        999999999,
        2147483647,
    ];

    public const int SqrtLutBits = 4;
    public static readonly ImmutableArray<int> SqrtLut = [
        131072, 110313,  97062,  87668,  80561,  74943,  70357,  66521,
         63251,  60421,  57939,  55740,  53774,  52002,  50394,  48927,
    ];
}
