// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Exanite.Core.Numerics;

public partial record struct Rect2Int
{
    public static readonly Rect2Int Zero = default;
    public static readonly Rect2Int One = FromSize(Vector2Int.One);

    public Vector2Int Offset;
    public Vector2Int Size;

    public static explicit operator Rect2Int(Rect2 value)
    {
        return FromOffsetSize((Vector2Int)value.Offset, (Vector2Int)value.Size);
    }

    public static explicit operator Rect2Int(Rect2Fixed value)
    {
        return FromOffsetSize((Vector2Int)value.Offset, (Vector2Int)value.Size);
    }

    public static Rect2Int FromSize(Vector2Int size)
    {
        return new Rect2Int()
        {
            Size = size,
        };
    }

    public static Rect2Int FromOffsetSize(Vector2Int offset, Vector2Int size)
    {
        return new Rect2Int()
        {
            Offset = offset,
            Size = size,
        };
    }

    public readonly Rect2Int Scale(Vector2Int scale)
    {
        return FromOffsetSize(scale * Offset, scale * Size);
    }

    public readonly bool Contains(Vector2Int position)
    {
        return position.X >= Offset.X && position.X < Offset.X + Size.X
            && position.Y >= Offset.Y && position.Y < Offset.Y + Size.Y;
    }

    public readonly bool Intersects(Rect2Int other)
    {
        return Offset.X < other.Offset.X + other.Size.X && Offset.X + Size.X > other.Offset.X
            && Offset.Y < other.Offset.Y + other.Size.Y && Offset.Y + Size.Y > other.Offset.Y;
    }
}
