// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Exanite.Core.Numerics;

public partial record struct Rect3Int
{
    public static readonly Rect3Int Zero = default;
    public static readonly Rect3Int One = FromSize(Vector3Int.One);

    public Vector3Int Offset;
    public Vector3Int Size;

    public static explicit operator Rect3Int(Rect3 value)
    {
        return FromOffsetSize((Vector3Int)value.Offset, (Vector3Int)value.Size);
    }

    public static explicit operator Rect3Int(Rect3Fixed value)
    {
        return FromOffsetSize((Vector3Int)value.Offset, (Vector3Int)value.Size);
    }

    public static Rect3Int FromSize(Vector3Int size)
    {
        return new Rect3Int()
        {
            Size = size,
        };
    }

    public static Rect3Int FromOffsetSize(Vector3Int offset, Vector3Int size)
    {
        return new Rect3Int()
        {
            Offset = offset,
            Size = size,
        };
    }

    public readonly Rect3Int Scale(Vector3Int scale)
    {
        return FromOffsetSize(scale * Offset, scale * Size);
    }

    public readonly bool Contains(Vector3Int position)
    {
        return position.X >= Offset.X && position.X < Offset.X + Size.X
            && position.Y >= Offset.Y && position.Y < Offset.Y + Size.Y
            && position.Z >= Offset.Z && position.Z < Offset.Z + Size.Z;
    }
}
