// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Exanite.Core.Numerics;

public partial record struct Rect3
{
    public static readonly Rect3 Zero = default;
    public static readonly Rect3 One = FromSize(Vector3.One);

    public Vector3 Offset;
    public Vector3 Size;

    public static explicit operator Rect3(Rect3Fixed value)
    {
        return FromOffsetSize((Vector3)value.Offset, (Vector3)value.Size);
    }

    public static implicit operator Rect3(Rect3Int value)
    {
        return FromOffsetSize((Vector3)value.Offset, (Vector3)value.Size);
    }

    public static Rect3 FromSize(Vector3 size)
    {
        return new Rect3()
        {
            Size = size,
        };
    }

    public static Rect3 FromOffsetSize(Vector3 offset, Vector3 size)
    {
        return new Rect3()
        {
            Offset = offset,
            Size = size,
        };
    }

    public readonly Rect3 Scale(Vector3 scale)
    {
        return FromOffsetSize(scale * Offset, scale * Size);
    }

    public readonly bool Contains(Vector3 position)
    {
        return position.X >= Offset.X && position.X < Offset.X + Size.X
            && position.Y >= Offset.Y && position.Y < Offset.Y + Size.Y
            && position.Z >= Offset.Z && position.Z < Offset.Z + Size.Z;
    }

    public readonly bool Intersects(Rect3 other)
    {
        return Offset.X < other.Offset.X + other.Size.X && Offset.X + Size.X > other.Offset.X
            && Offset.Y < other.Offset.Y + other.Size.Y && Offset.Y + Size.Y > other.Offset.Y
            && Offset.Z < other.Offset.Z + other.Size.Z && Offset.Z + Size.Z > other.Offset.Z;
    }
}
