// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Exanite.Core.Numerics;

public partial record struct Rect3
{
    public static readonly Rect3 Zero = default;
    public static readonly Rect3 One = FromSize(Vector3.One);

    public Vector3 Offset;
    public Vector3 Size;

    public static explicit operator Rect3Fixed(Rect3 value)
    {
        return Rect3Fixed.FromOffsetSize((Vector3Fixed)value.Offset, (Vector3Fixed)value.Size);
    }

    public static explicit operator Rect3Int(Rect3 value)
    {
        return Rect3Int.FromOffsetSize((Vector3Int)value.Offset, (Vector3Int)value.Size);
    }

    public static Rect3 FromSize(Vector3 size)
    {
        return new Rect3()
        {
            Size = size,
        };
    }

    public static Rect3 FromOffsetSize(Vector3 offset, Vector3 size)
    {
        return new Rect3()
        {
            Offset = offset,
            Size = size,
        };
    }

    public readonly Rect3 Scale(Vector3 scale)
    {
        return FromOffsetSize(scale * Offset, scale * Size);
    }

    public readonly bool Contains(Vector3 position)
    {
        return position.X >= Offset.X && position.X < Offset.X + Size.X
            && position.Y >= Offset.Y && position.Y < Offset.Y + Size.Y
            && position.Z >= Offset.Z && position.Z < Offset.Z + Size.Z;
    }
}
