// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Exanite.Core.Numerics;

public partial record struct Rect2Fixed
{
    public static readonly Rect2Fixed Zero = default;
    public static readonly Rect2Fixed One = FromSize(Vector2Fixed.One);

    public Vector2Fixed Offset;
    public Vector2Fixed Size;

    public static explicit operator Rect2(Rect2Fixed value)
    {
        return Rect2.FromOffsetSize((Vector2)value.Offset, (Vector2)value.Size);
    }

    public static explicit operator Rect2Fixed(Rect2 value)
    {
        return Rect2Fixed.FromOffsetSize((Vector2Fixed)value.Offset, (Vector2Fixed)value.Size);
    }

    public static Rect2Fixed FromSize(Vector2Fixed size)
    {
        return new Rect2Fixed()
        {
            Size = size,
        };
    }

    public static Rect2Fixed FromOffsetSize(Vector2Fixed offset, Vector2Fixed size)
    {
        return new Rect2Fixed()
        {
            Offset = offset,
            Size = size,
        };
    }

    public readonly Rect2Fixed Scale(Vector2Fixed scale)
    {
        return FromOffsetSize(scale * Offset, scale * Size);
    }

    public readonly bool Contains(Vector2Fixed position)
    {
        return position.X >= Offset.X && position.X < Offset.X + Size.X
            && position.Y >= Offset.Y && position.Y < Offset.Y + Size.Y;
    }
}
