// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Exanite.Core.Numerics;

public partial record struct Rect3Fixed
{
    public static readonly Rect3Fixed Zero = default;
    public static readonly Rect3Fixed One = FromSize(Vector3Fixed.One);

    public Vector3Fixed Offset;
    public Vector3Fixed Size;

    public static explicit operator Rect3Fixed(Rect3 value)
    {
        return FromOffsetSize((Vector3Fixed)value.Offset, (Vector3Fixed)value.Size);
    }

    public static implicit operator Rect3Fixed(Rect3Int value)
    {
        return FromOffsetSize((Vector3Fixed)value.Offset, (Vector3Fixed)value.Size);
    }

    public static Rect3Fixed FromSize(Vector3Fixed size)
    {
        return new Rect3Fixed()
        {
            Size = size,
        };
    }

    public static Rect3Fixed FromOffsetSize(Vector3Fixed offset, Vector3Fixed size)
    {
        return new Rect3Fixed()
        {
            Offset = offset,
            Size = size,
        };
    }

    public readonly Rect3Fixed Scale(Vector3Fixed scale)
    {
        return FromOffsetSize(scale * Offset, scale * Size);
    }

    public readonly bool Contains(Vector3Fixed position)
    {
        return position.X >= Offset.X && position.X < Offset.X + Size.X
            && position.Y >= Offset.Y && position.Y < Offset.Y + Size.Y
            && position.Z >= Offset.Z && position.Z < Offset.Z + Size.Z;
    }

    public readonly bool Intersects(Rect3Fixed other)
    {
        return Offset.X < other.Offset.X + other.Size.X && Offset.X + Size.X > other.Offset.X
            && Offset.Y < other.Offset.Y + other.Size.Y && Offset.Y + Size.Y > other.Offset.Y
            && Offset.Z < other.Offset.Z + other.Size.Z && Offset.Z + Size.Z > other.Offset.Z;
    }
}
