// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Exanite.Core.Numerics;

public partial record struct Rect3Fixed
{
    public static readonly Rect3Fixed Zero = default;
    public static readonly Rect3Fixed One = FromSize(Vector3Fixed.One);

    public Vector3Fixed Offset;
    public Vector3Fixed Size;

    public static explicit operator Rect3(Rect3Fixed value)
    {
        return Rect3.FromOffsetSize((Vector3)value.Offset, (Vector3)value.Size);
    }

    public static explicit operator Rect3Int(Rect3Fixed value)
    {
        return Rect3Int.FromOffsetSize((Vector3Int)value.Offset, (Vector3Int)value.Size);
    }

    public static Rect3Fixed FromSize(Vector3Fixed size)
    {
        return new Rect3Fixed()
        {
            Size = size,
        };
    }

    public static Rect3Fixed FromOffsetSize(Vector3Fixed offset, Vector3Fixed size)
    {
        return new Rect3Fixed()
        {
            Offset = offset,
            Size = size,
        };
    }

    public readonly Rect3Fixed Scale(Vector3Fixed scale)
    {
        return FromOffsetSize(scale * Offset, scale * Size);
    }

    public readonly bool Contains(Vector3Fixed position)
    {
        return position.X >= Offset.X && position.X < Offset.X + Size.X
            && position.Y >= Offset.Y && position.Y < Offset.Y + Size.Y
            && position.Z >= Offset.Z && position.Z < Offset.Z + Size.Z;
    }
}
