// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Exanite.Core.Numerics;

public partial record struct Rect2
{
    public static readonly Rect2 Zero = default;
    public static readonly Rect2 One = FromSize(Vector2.One);

    public Vector2 Offset;
    public Vector2 Size;

    public static explicit operator Rect2(Rect2Fixed value)
    {
        return FromOffsetSize((Vector2)value.Offset, (Vector2)value.Size);
    }

    public static implicit operator Rect2(Rect2Int value)
    {
        return FromOffsetSize((Vector2)value.Offset, (Vector2)value.Size);
    }

    public static Rect2 FromSize(Vector2 size)
    {
        return new Rect2()
        {
            Size = size,
        };
    }

    public static Rect2 FromOffsetSize(Vector2 offset, Vector2 size)
    {
        return new Rect2()
        {
            Offset = offset,
            Size = size,
        };
    }

    public readonly Rect2 Scale(Vector2 scale)
    {
        return FromOffsetSize(scale * Offset, scale * Size);
    }

    public readonly bool Contains(Vector2 position)
    {
        return position.X >= Offset.X && position.X < Offset.X + Size.X
            && position.Y >= Offset.Y && position.Y < Offset.Y + Size.Y;
    }

    public readonly bool Intersects(Rect2 other)
    {
        return Offset.X < other.Offset.X + other.Size.X && Offset.X + Size.X > other.Offset.X
            && Offset.Y < other.Offset.Y + other.Size.Y && Offset.Y + Size.Y > other.Offset.Y;
    }
}
