// <auto-generated/>
#nullable enable

using System.Numerics;

namespace Exanite.Core.Numerics;

public partial record struct Rect2Int
{
    public static readonly Rect2Int Zero = default;
    public static readonly Rect2Int One = FromSize(Vector2Int.One);

    public Vector2Int Offset;
    public Vector2Int Size;

    public static implicit operator Rect2(Rect2Int value)
    {
        return Rect2.FromOffsetSize((Vector2)value.Offset, (Vector2)value.Size);
    }

    public static implicit operator Rect2Fixed(Rect2Int value)
    {
        return Rect2Fixed.FromOffsetSize((Vector2Fixed)value.Offset, (Vector2Fixed)value.Size);
    }

    public static Rect2Int FromSize(Vector2Int size)
    {
        return new Rect2Int()
        {
            Size = size,
        };
    }

    public static Rect2Int FromOffsetSize(Vector2Int offset, Vector2Int size)
    {
        return new Rect2Int()
        {
            Offset = offset,
            Size = size,
        };
    }

    public readonly Rect2Int Scale(Vector2Int scale)
    {
        return FromOffsetSize(scale * Offset, scale * Size);
    }

    public readonly bool Contains(Vector2Int position)
    {
        return position.X >= Offset.X && position.X < Offset.X + Size.X
            && position.Y >= Offset.Y && position.Y < Offset.Y + Size.Y;
    }
}
