// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Numerics;
using System.Runtime.InteropServices;

namespace Exanite.Core.Numerics;

public partial struct Vector2Fixed
{
    /// <inheritdoc cref="Vector2.X"/>
    public Fixed X;

    /// <inheritdoc cref="Vector2.Y"/>
    public Fixed Y;

    /// <inheritdoc cref="Vector2.Zero"/>
    public static Vector2Fixed Zero => default;

    /// <inheritdoc cref="Vector2.One"/>
    public static Vector2Fixed One => new(1);

    /// <inheritdoc cref="Vector2.UnitX"/>
    public static Vector2Fixed UnitX => new(1, 0);

    /// <inheritdoc cref="Vector2.UnitY"/>
    public static Vector2Fixed UnitY => new(0, 1);

    public Fixed this[int index]
    {
        readonly get
        {
            switch (index)
            {
                case 0: return X;
                case 1: return Y;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }

        set
        {
            switch (index)
            {
                case 0: X = value; break;
                case 1: Y = value; break;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }
    }

    public Vector2Fixed(Fixed value) : this(value, value) {}

    public Vector2Fixed(Fixed x, Fixed y)
    {
        X = x;
        Y = y;
    }
}
