// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Numerics;
using System.Runtime.InteropServices;

namespace Exanite.Core.Numerics;

public struct Vector4Int : IEquatable<Vector4Int>, IFormattable
{
    /// <inheritdoc cref="Vector4.X"/>
    public int X;

    /// <inheritdoc cref="Vector4.Y"/>
    public int Y;

    /// <inheritdoc cref="Vector4.Z"/>
    public int Z;

    /// <inheritdoc cref="Vector4.W"/>
    public int W;

    /// <inheritdoc cref="Vector4.Zero"/>
    public static Vector4Int Zero => default;

    /// <inheritdoc cref="Vector4.One"/>
    public static Vector4Int One => new(1);

    /// <inheritdoc cref="Vector4.UnitX"/>
    public static Vector4Int UnitX => new(1, 0, 0, 0);

    /// <inheritdoc cref="Vector4.UnitY"/>
    public static Vector4Int UnitY => new(0, 1, 0, 0);

    /// <inheritdoc cref="Vector4.UnitZ"/>
    public static Vector4Int UnitZ => new(0, 0, 1, 0);

    /// <inheritdoc cref="Vector4.UnitW"/>
    public static Vector4Int UnitW => new(0, 0, 0, 1);

    public int this[int index]
    {
        readonly get
        {
            switch (index)
            {
                case 0: return X;
                case 1: return Y;
                case 2: return Z;
                case 3: return W;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }

        set
        {
            switch (index)
            {
                case 0: X = value; break;
                case 1: Y = value; break;
                case 2: Z = value; break;
                case 3: W = value; break;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }
    }

    public Vector4Int(int value) : this(value, value, value, value) {}

    public Vector4Int(int x, int y, int z, int w)
    {
        X = x;
        Y = y;
        Z = z;
        W = w;
    }

    public static explicit operator Vector4Int(Vector4 value)
    {
        return new Vector4Int((int)value.X, (int)value.Y, (int)value.Z, (int)value.W);
    }

    public static implicit operator Vector4(Vector4Int value)
    {
        return new Vector4(value.X, value.Y, value.Z, value.W);
    }

    public static Vector4Int operator *(Vector4Int value, int scalar)
    {
        return new Vector4Int(value.X * scalar, value.Y * scalar, value.Z * scalar, value.W * scalar);
    }

    public static Vector4 operator *(Vector4Int value, float scalar)
    {
        return new Vector4(value.X * scalar, value.Y * scalar, value.Z * scalar, value.W * scalar);
    }

    public static Vector4Int operator /(Vector4Int value, int scalar)
    {
        return new Vector4Int(value.X / scalar, value.Y / scalar, value.Z / scalar, value.W / scalar);
    }

    public static Vector4 operator /(Vector4Int value, float scalar)
    {
        return new Vector4(value.X / scalar, value.Y / scalar, value.Z / scalar, value.W / scalar);
    }

    public static Vector4Int operator +(Vector4Int left, Vector4Int right)
    {
        return new Vector4Int(left.X + right.X, left.Y + right.Y, left.Z + right.Z, left.W + right.W);
    }

    public static Vector4Int operator -(Vector4Int left, Vector4Int right)
    {
        return new Vector4Int(left.X - right.X, left.Y - right.Y, left.Z - right.Z, left.W - right.W);
    }

    public static Vector4Int operator *(Vector4Int left, Vector4Int right)
    {
        return new Vector4Int(left.X * right.X, left.Y * right.Y, left.Z * right.Z, left.W * right.W);
    }

    public static Vector4Int operator /(Vector4Int left, Vector4Int right)
    {
        return new Vector4Int(left.X / right.X, left.Y / right.Y, left.Z / right.Z, left.W / right.W);
    }

    public static Vector4Int operator <<(Vector4Int left, Vector4Int right)
    {
        return new Vector4Int(left.X << right.X, left.Y << right.Y, left.Z << right.Z, left.W << right.W);
    }

    public static Vector4Int operator >>(Vector4Int left, Vector4Int right)
    {
        return new Vector4Int(left.X >> right.X, left.Y >> right.Y, left.Z >> right.Z, left.W >> right.W);
    }

    public static Vector4Int operator >>>(Vector4Int left, Vector4Int right)
    {
        return new Vector4Int(left.X >>> right.X, left.Y >>> right.Y, left.Z >>> right.Z, left.W >>> right.W);
    }

    public static Vector4Int operator &(Vector4Int left, Vector4Int right)
    {
        return new Vector4Int(left.X & right.X, left.Y & right.Y, left.Z & right.Z, left.W & right.W);
    }

    public static Vector4Int operator |(Vector4Int left, Vector4Int right)
    {
        return new Vector4Int(left.X | right.X, left.Y | right.Y, left.Z | right.Z, left.W | right.W);
    }

    public static Vector4Int operator ^(Vector4Int left, Vector4Int right)
    {
        return new Vector4Int(left.X ^ right.X, left.Y ^ right.Y, left.Z ^ right.Z, left.W ^ right.W);
    }

    public static Vector4Int operator -(Vector4Int value)
    {
        return Zero - value;
    }

    public static bool operator ==(Vector4Int left, Vector4Int right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(Vector4Int left, Vector4Int right)
    {
        return !left.Equals(right);
    }

    public bool Equals(Vector4Int other)
    {
        return X == other.X && Y == other.Y && Z == other.Z && W == other.W;
    }

    public override bool Equals(object? obj)
    {
        return obj is Vector4Int other && Equals(other);
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(X, Y, Z, W);
    }

    public override string ToString()
    {
        return ToString("G", CultureInfo.CurrentCulture);
    }

    public string ToString([StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format)
    {
        return ToString(format, CultureInfo.CurrentCulture);
    }

    public string ToString([StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format, IFormatProvider? formatProvider)
    {
        return ((Vector4)this).ToString(format, formatProvider);
    }
}
