// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Numerics;
using System.Runtime.InteropServices;

namespace Exanite.Core.Numerics;

public partial struct Vector2Int : IEquatable<Vector2Int>, IFormattable
{
    /// <inheritdoc cref="Vector2.X"/>
    public int X;

    /// <inheritdoc cref="Vector2.Y"/>
    public int Y;

    /// <inheritdoc cref="Vector2.Zero"/>
    public static Vector2Int Zero => default;

    /// <inheritdoc cref="Vector2.One"/>
    public static Vector2Int One => new(1);

    /// <inheritdoc cref="Vector2.UnitX"/>
    public static Vector2Int UnitX => new(1, 0);

    /// <inheritdoc cref="Vector2.UnitY"/>
    public static Vector2Int UnitY => new(0, 1);

    public int this[int index]
    {
        readonly get
        {
            switch (index)
            {
                case 0: return X;
                case 1: return Y;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }

        set
        {
            switch (index)
            {
                case 0: X = value; break;
                case 1: Y = value; break;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }
    }

    public Vector2Int(int value) : this(value, value) {}

    public Vector2Int(int x, int y)
    {
        X = x;
        Y = y;
    }

    public static explicit operator Vector2Int(Vector2 value)
    {
        return new Vector2Int((int)value.X, (int)value.Y);
    }

    public static implicit operator Vector2(Vector2Int value)
    {
        return new Vector2(value.X, value.Y);
    }

    public static Vector2Int operator *(Vector2Int value, int scalar)
    {
        return new Vector2Int(value.X * scalar, value.Y * scalar);
    }

    public static Vector2 operator *(Vector2Int value, float scalar)
    {
        return new Vector2(value.X * scalar, value.Y * scalar);
    }

    public static Vector2Int operator /(Vector2Int value, int scalar)
    {
        return new Vector2Int(value.X / scalar, value.Y / scalar);
    }

    public static Vector2 operator /(Vector2Int value, float scalar)
    {
        return new Vector2(value.X / scalar, value.Y / scalar);
    }

    public static Vector2Int operator +(Vector2Int left, Vector2Int right)
    {
        return new Vector2Int(left.X + right.X, left.Y + right.Y);
    }

    public static Vector2Int operator -(Vector2Int left, Vector2Int right)
    {
        return new Vector2Int(left.X - right.X, left.Y - right.Y);
    }

    public static Vector2Int operator *(Vector2Int left, Vector2Int right)
    {
        return new Vector2Int(left.X * right.X, left.Y * right.Y);
    }

    public static Vector2Int operator /(Vector2Int left, Vector2Int right)
    {
        return new Vector2Int(left.X / right.X, left.Y / right.Y);
    }

    public static Vector2Int operator %(Vector2Int left, Vector2Int right)
    {
        return new Vector2Int(left.X % right.X, left.Y % right.Y);
    }

    public static Vector2Int operator <<(Vector2Int left, Vector2Int right)
    {
        return new Vector2Int(left.X << right.X, left.Y << right.Y);
    }

    public static Vector2Int operator >>(Vector2Int left, Vector2Int right)
    {
        return new Vector2Int(left.X >> right.X, left.Y >> right.Y);
    }

    public static Vector2Int operator >>>(Vector2Int left, Vector2Int right)
    {
        return new Vector2Int(left.X >>> right.X, left.Y >>> right.Y);
    }

    public static Vector2Int operator &(Vector2Int left, Vector2Int right)
    {
        return new Vector2Int(left.X & right.X, left.Y & right.Y);
    }

    public static Vector2Int operator |(Vector2Int left, Vector2Int right)
    {
        return new Vector2Int(left.X | right.X, left.Y | right.Y);
    }

    public static Vector2Int operator ^(Vector2Int left, Vector2Int right)
    {
        return new Vector2Int(left.X ^ right.X, left.Y ^ right.Y);
    }

    public static Vector2Int operator -(Vector2Int value)
    {
        return Zero - value;
    }

    public static bool operator ==(Vector2Int left, Vector2Int right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(Vector2Int left, Vector2Int right)
    {
        return !left.Equals(right);
    }

    public bool Equals(Vector2Int other)
    {
        return X == other.X && Y == other.Y;
    }

    public override bool Equals(object? obj)
    {
        return obj is Vector2Int other && Equals(other);
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(X, Y);
    }

    public override string ToString()
    {
        return ToString("G", CultureInfo.CurrentCulture);
    }

    public string ToString([StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format)
    {
        return ToString(format, CultureInfo.CurrentCulture);
    }

    public string ToString([StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format, IFormatProvider? formatProvider)
    {
        string separator = NumberFormatInfo.GetInstance(formatProvider).NumberGroupSeparator;

        return $"<{X.ToString(format, formatProvider)}{separator} {Y.ToString(format, formatProvider)}>";
    }
}
