// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Numerics;
using System.Runtime.InteropServices;

namespace Exanite.Core.Numerics;

public partial struct Vector4Fixed
{
    /// <inheritdoc cref="Vector4.X"/>
    public Fixed X;

    /// <inheritdoc cref="Vector4.Y"/>
    public Fixed Y;

    /// <inheritdoc cref="Vector4.Z"/>
    public Fixed Z;

    /// <inheritdoc cref="Vector4.W"/>
    public Fixed W;

    /// <inheritdoc cref="Vector4.Zero"/>
    public static Vector4Fixed Zero => default;

    /// <inheritdoc cref="Vector4.One"/>
    public static Vector4Fixed One => new(1);

    /// <inheritdoc cref="Vector4.UnitX"/>
    public static Vector4Fixed UnitX => new(1, 0, 0, 0);

    /// <inheritdoc cref="Vector4.UnitY"/>
    public static Vector4Fixed UnitY => new(0, 1, 0, 0);

    /// <inheritdoc cref="Vector4.UnitZ"/>
    public static Vector4Fixed UnitZ => new(0, 0, 1, 0);

    /// <inheritdoc cref="Vector4.UnitW"/>
    public static Vector4Fixed UnitW => new(0, 0, 0, 1);

    public Fixed this[int index]
    {
        readonly get
        {
            switch (index)
            {
                case 0: return X;
                case 1: return Y;
                case 2: return Z;
                case 3: return W;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }

        set
        {
            switch (index)
            {
                case 0: X = value; break;
                case 1: Y = value; break;
                case 2: Z = value; break;
                case 3: W = value; break;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }
    }

    public Vector4Fixed(Fixed value) : this(value, value, value, value) {}

    public Vector4Fixed(Fixed x, Fixed y, Fixed z, Fixed w)
    {
        X = x;
        Y = y;
        Z = z;
        W = w;
    }
}
