// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Numerics;
using System.Runtime.InteropServices;

namespace Exanite.Core.Numerics;

public partial struct Vector3Fixed : IEquatable<Vector3Fixed>, IFormattable
{
    /// <inheritdoc cref="Vector3.X"/>
    public Fixed X;

    /// <inheritdoc cref="Vector3.Y"/>
    public Fixed Y;

    /// <inheritdoc cref="Vector3.Z"/>
    public Fixed Z;

    /// <inheritdoc cref="Vector3.Zero"/>
    public static Vector3Fixed Zero => default;

    /// <inheritdoc cref="Vector3.One"/>
    public static Vector3Fixed One => new(1);

    /// <inheritdoc cref="Vector3.UnitX"/>
    public static Vector3Fixed UnitX => new(1, 0, 0);

    /// <inheritdoc cref="Vector3.UnitY"/>
    public static Vector3Fixed UnitY => new(0, 1, 0);

    /// <inheritdoc cref="Vector3.UnitZ"/>
    public static Vector3Fixed UnitZ => new(0, 0, 1);

    public Fixed this[int index]
    {
        readonly get
        {
            switch (index)
            {
                case 0: return X;
                case 1: return Y;
                case 2: return Z;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }

        set
        {
            switch (index)
            {
                case 0: X = value; break;
                case 1: Y = value; break;
                case 2: Z = value; break;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }
    }

    public Vector3Fixed(Fixed value) : this(value, value, value) {}

    public Vector3Fixed(Fixed x, Fixed y, Fixed z)
    {
        X = x;
        Y = y;
        Z = z;
    }

    // Conversion: Safe - No precision loss possible
    public static implicit operator Vector3Fixed(Vector3Int value)
    {
        return new Vector3Fixed((Fixed)value.X, (Fixed)value.Y, (Fixed)value.Z);
    }

    // Conversion: Unsafe - Non-deterministic
    // Consider using Fixed.FromParts or Fixed.FromFraction instead
    public static explicit operator Vector3Fixed(Vector3 value)
    {
        return new Vector3Fixed((Fixed)value.X, (Fixed)value.Y, (Fixed)value.Z);
    }

    // Conversion: Loss of fraction
    public static explicit operator Vector3Int(Vector3Fixed value)
    {
        return new Vector3Int((int)value.X, (int)value.Y, (int)value.Z);
    }

    // Conversion: Loss of precision / determinism
    public static explicit operator Vector3(Vector3Fixed value)
    {
        return new Vector3((float)value.X, (float)value.Y, (float)value.Z);
    }

    public static Vector3Fixed operator *(Vector3Fixed value, Fixed scalar)
    {
        return new Vector3Fixed(value.X * scalar, value.Y * scalar, value.Z * scalar);
    }

    public static Vector3Fixed operator /(Vector3Fixed value, Fixed scalar)
    {
        return new Vector3Fixed(value.X / scalar, value.Y / scalar, value.Z / scalar);
    }

    public static Vector3Fixed operator +(Vector3Fixed left, Vector3Fixed right)
    {
        return new Vector3Fixed(left.X + right.X, left.Y + right.Y, left.Z + right.Z);
    }

    public static Vector3Fixed operator -(Vector3Fixed left, Vector3Fixed right)
    {
        return new Vector3Fixed(left.X - right.X, left.Y - right.Y, left.Z - right.Z);
    }

    public static Vector3Fixed operator *(Vector3Fixed left, Vector3Fixed right)
    {
        return new Vector3Fixed(left.X * right.X, left.Y * right.Y, left.Z * right.Z);
    }

    public static Vector3Fixed operator /(Vector3Fixed left, Vector3Fixed right)
    {
        return new Vector3Fixed(left.X / right.X, left.Y / right.Y, left.Z / right.Z);
    }

    public static Vector3Fixed operator %(Vector3Fixed left, Vector3Fixed right)
    {
        return new Vector3Fixed(left.X % right.X, left.Y % right.Y, left.Z % right.Z);
    }

    public static Vector3Fixed operator -(Vector3Fixed value)
    {
        return Zero - value;
    }

    public static Fixed Length(Vector3Fixed value)
    {
        return Fixed.Hypot(value.X, value.Y, value.Z);
    }

    public static Vector3Fixed Normalize(Vector3Fixed value)
    {
        return value / Vector3Fixed.Length(value);
    }

    public static bool operator ==(Vector3Fixed left, Vector3Fixed right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(Vector3Fixed left, Vector3Fixed right)
    {
        return !left.Equals(right);
    }

    public bool Equals(Vector3Fixed other)
    {
        return X == other.X && Y == other.Y && Z == other.Z;
    }

    public override bool Equals(object? obj)
    {
        return obj is Vector3Fixed other && Equals(other);
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(X, Y, Z);
    }

    public override string ToString()
    {
        return ToString("G", CultureInfo.CurrentCulture);
    }

    public string ToString([StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format)
    {
        return ToString(format, CultureInfo.CurrentCulture);
    }

    public string ToString([StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format, IFormatProvider? formatProvider)
    {
        string separator = NumberFormatInfo.GetInstance(formatProvider).NumberGroupSeparator;

        return $"<{X.ToString(format, formatProvider)}{separator} {Y.ToString(format, formatProvider)}{separator} {Z.ToString(format, formatProvider)}>";
    }
}
