// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Numerics;
using System.Runtime.InteropServices;

namespace Exanite.Core.Numerics;

public partial struct Vector4Fixed
{
    /// <inheritdoc cref="Vector4.X"/>
    public Fixed X;

    /// <inheritdoc cref="Vector4.Y"/>
    public Fixed Y;

    /// <inheritdoc cref="Vector4.Z"/>
    public Fixed Z;

    /// <inheritdoc cref="Vector4.W"/>
    public Fixed W;

    /// <inheritdoc cref="Vector4.Zero"/>
    public static Vector4Fixed Zero => default;

    /// <inheritdoc cref="Vector4.One"/>
    public static Vector4Fixed One => new(1);

    /// <inheritdoc cref="Vector4.UnitX"/>
    public static Vector4Fixed UnitX => new(1, 0, 0, 0);

    /// <inheritdoc cref="Vector4.UnitY"/>
    public static Vector4Fixed UnitY => new(0, 1, 0, 0);

    /// <inheritdoc cref="Vector4.UnitZ"/>
    public static Vector4Fixed UnitZ => new(0, 0, 1, 0);

    /// <inheritdoc cref="Vector4.UnitW"/>
    public static Vector4Fixed UnitW => new(0, 0, 0, 1);

    public Fixed this[int index]
    {
        readonly get
        {
            switch (index)
            {
                case 0: return X;
                case 1: return Y;
                case 2: return Z;
                case 3: return W;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }

        set
        {
            switch (index)
            {
                case 0: X = value; break;
                case 1: Y = value; break;
                case 2: Z = value; break;
                case 3: W = value; break;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }
    }

    public Vector4Fixed(Fixed value) : this(value, value, value, value) {}

    public Vector4Fixed(Fixed x, Fixed y, Fixed z, Fixed w)
    {
        X = x;
        Y = y;
        Z = z;
        W = w;
    }

    // Conversion: Safe - No precision loss possible
    public static implicit operator Vector4Fixed(Vector4Int value)
    {
        return new Vector4Fixed(value.X, value.Y, value.Z, value.W);
    }

    // Conversion: Unsafe - Non-deterministic
    // Consider using FromFraction instead
    public static explicit operator Vector4Fixed(Vector4 value)
    {
        return new Vector4Fixed((Fixed)value.X, (Fixed)value.Y, (Fixed)value.Z, (Fixed)value.W);
    }

    // Conversion: Loss of fraction
    public static explicit operator Vector4Int(Vector4Fixed value)
    {
        return new Vector4Int((int)value.X, (int)value.Y, (int)value.Z, (int)value.W);
    }

    // Conversion: Loss of precision
    public static explicit operator Vector4(Vector4Fixed value)
    {
        return new Vector4((float)value.X, (float)value.Y, (float)value.Z, (float)value.W);
    }

    public static Vector4Fixed operator *(Vector4Fixed value, Fixed scalar)
    {
        return new Vector4Fixed(value.X * scalar, value.Y * scalar, value.Z * scalar, value.W * scalar);
    }

    public static Vector4Fixed operator /(Vector4Fixed value, Fixed scalar)
    {
        return new Vector4Fixed(value.X / scalar, value.Y / scalar, value.Z / scalar, value.W / scalar);
    }

    public static Vector4Fixed operator +(Vector4Fixed left, Vector4Fixed right)
    {
        return new Vector4Fixed(left.X + right.X, left.Y + right.Y, left.Z + right.Z, left.W + right.W);
    }

    public static Vector4Fixed operator -(Vector4Fixed left, Vector4Fixed right)
    {
        return new Vector4Fixed(left.X - right.X, left.Y - right.Y, left.Z - right.Z, left.W - right.W);
    }

    public static Vector4Fixed operator *(Vector4Fixed left, Vector4Fixed right)
    {
        return new Vector4Fixed(left.X * right.X, left.Y * right.Y, left.Z * right.Z, left.W * right.W);
    }

    public static Vector4Fixed operator /(Vector4Fixed left, Vector4Fixed right)
    {
        return new Vector4Fixed(left.X / right.X, left.Y / right.Y, left.Z / right.Z, left.W / right.W);
    }

    public static Vector4Fixed operator %(Vector4Fixed left, Vector4Fixed right)
    {
        return new Vector4Fixed(left.X % right.X, left.Y % right.Y, left.Z % right.Z, left.W % right.W);
    }

    public static Vector4Fixed operator -(Vector4Fixed value)
    {
        return Zero - value;
    }

    public static bool operator ==(Vector4Fixed left, Vector4Fixed right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(Vector4Fixed left, Vector4Fixed right)
    {
        return !left.Equals(right);
    }

    public bool Equals(Vector4Fixed other)
    {
        return X == other.X && Y == other.Y && Z == other.Z && W == other.W;
    }

    public override bool Equals(object? obj)
    {
        return obj is Vector4Fixed other && Equals(other);
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(X, Y, Z, W);
    }
}
