// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Numerics;
using System.Runtime.InteropServices;

namespace Exanite.Core.Numerics;

public partial struct Vector3Int : IEquatable<Vector3Int>, IFormattable
{
    /// <inheritdoc cref="Vector3.X"/>
    public int X;

    /// <inheritdoc cref="Vector3.Y"/>
    public int Y;

    /// <inheritdoc cref="Vector3.Z"/>
    public int Z;

    /// <inheritdoc cref="Vector3.Zero"/>
    public static Vector3Int Zero => default;

    /// <inheritdoc cref="Vector3.One"/>
    public static Vector3Int One => new(1);

    /// <inheritdoc cref="Vector3.UnitX"/>
    public static Vector3Int UnitX => new(1, 0, 0);

    /// <inheritdoc cref="Vector3.UnitY"/>
    public static Vector3Int UnitY => new(0, 1, 0);

    /// <inheritdoc cref="Vector3.UnitZ"/>
    public static Vector3Int UnitZ => new(0, 0, 1);

    public int this[int index]
    {
        readonly get
        {
            switch (index)
            {
                case 0: return X;
                case 1: return Y;
                case 2: return Z;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }

        set
        {
            switch (index)
            {
                case 0: X = value; break;
                case 1: Y = value; break;
                case 2: Z = value; break;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }
    }

    public Vector3Int(int value) : this(value, value, value) {}

    public Vector3Int(int x, int y, int z)
    {
        X = x;
        Y = y;
        Z = z;
    }

    public static explicit operator Vector3Int(Vector3 value)
    {
        return new Vector3Int((int)value.X, (int)value.Y, (int)value.Z);
    }

    public static implicit operator Vector3(Vector3Int value)
    {
        return new Vector3((float)value.X, (float)value.Y, (float)value.Z);
    }

    public static Vector3Int operator *(Vector3Int value, int scalar)
    {
        return new Vector3Int(value.X * scalar, value.Y * scalar, value.Z * scalar);
    }

    public static Vector3 operator *(Vector3Int value, float scalar)
    {
        return new Vector3(value.X * scalar, value.Y * scalar, value.Z * scalar);
    }

    public static Vector3Int operator /(Vector3Int value, int scalar)
    {
        return new Vector3Int(value.X / scalar, value.Y / scalar, value.Z / scalar);
    }

    public static Vector3 operator /(Vector3Int value, float scalar)
    {
        return new Vector3(value.X / scalar, value.Y / scalar, value.Z / scalar);
    }

    public static Vector3Int operator +(Vector3Int left, Vector3Int right)
    {
        return new Vector3Int(left.X + right.X, left.Y + right.Y, left.Z + right.Z);
    }

    public static Vector3Int operator -(Vector3Int left, Vector3Int right)
    {
        return new Vector3Int(left.X - right.X, left.Y - right.Y, left.Z - right.Z);
    }

    public static Vector3Int operator *(Vector3Int left, Vector3Int right)
    {
        return new Vector3Int(left.X * right.X, left.Y * right.Y, left.Z * right.Z);
    }

    public static Vector3Int operator /(Vector3Int left, Vector3Int right)
    {
        return new Vector3Int(left.X / right.X, left.Y / right.Y, left.Z / right.Z);
    }

    public static Vector3Int operator %(Vector3Int left, Vector3Int right)
    {
        return new Vector3Int(left.X % right.X, left.Y % right.Y, left.Z % right.Z);
    }

    public static Vector3Int operator <<(Vector3Int left, Vector3Int right)
    {
        return new Vector3Int(left.X << right.X, left.Y << right.Y, left.Z << right.Z);
    }

    public static Vector3Int operator >>(Vector3Int left, Vector3Int right)
    {
        return new Vector3Int(left.X >> right.X, left.Y >> right.Y, left.Z >> right.Z);
    }

    public static Vector3Int operator >>>(Vector3Int left, Vector3Int right)
    {
        return new Vector3Int(left.X >>> right.X, left.Y >>> right.Y, left.Z >>> right.Z);
    }

    public static Vector3Int operator &(Vector3Int left, Vector3Int right)
    {
        return new Vector3Int(left.X & right.X, left.Y & right.Y, left.Z & right.Z);
    }

    public static Vector3Int operator |(Vector3Int left, Vector3Int right)
    {
        return new Vector3Int(left.X | right.X, left.Y | right.Y, left.Z | right.Z);
    }

    public static Vector3Int operator ^(Vector3Int left, Vector3Int right)
    {
        return new Vector3Int(left.X ^ right.X, left.Y ^ right.Y, left.Z ^ right.Z);
    }

    public static Vector3Int operator -(Vector3Int value)
    {
        return Zero - value;
    }

    /// <inheritdoc cref="Vector3.Dot"/>
    public static int Dot(Vector3Int left, Vector3Int right)
    {
        return left.X * right.X + left.Y * right.Y + left.Z * right.Z;
    }

    /// <inheritdoc cref="Vector3.Cross"/>
    public static Vector3Int Cross(Vector3Int left, Vector3Int right)
    {
        return new Vector3Int(
            (left.Y * right.Z) - (left.Z * right.Y),
            (left.Z * right.X) - (left.X * right.Z),
            (left.X * right.Y) - (left.Y * right.X)
        );
    }

    public static bool operator ==(Vector3Int left, Vector3Int right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(Vector3Int left, Vector3Int right)
    {
        return !left.Equals(right);
    }

    public bool Equals(Vector3Int other)
    {
        return X == other.X && Y == other.Y && Z == other.Z;
    }

    public override bool Equals(object? obj)
    {
        return obj is Vector3Int other && Equals(other);
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(X, Y, Z);
    }

    public override string ToString()
    {
        return ToString("G", CultureInfo.CurrentCulture);
    }

    public string ToString([StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format)
    {
        return ToString(format, CultureInfo.CurrentCulture);
    }

    public string ToString([StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format, IFormatProvider? formatProvider)
    {
        string separator = NumberFormatInfo.GetInstance(formatProvider).NumberGroupSeparator;

        return $"<{X.ToString(format, formatProvider)}{separator} {Y.ToString(format, formatProvider)}{separator} {Z.ToString(format, formatProvider)}>";
    }
}
