// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Numerics;
using System.Runtime.InteropServices;

namespace Exanite.Core.Numerics;

public partial struct Vector3Fixed
{
    /// <inheritdoc cref="Vector3.X"/>
    public Fixed X;

    /// <inheritdoc cref="Vector3.Y"/>
    public Fixed Y;

    /// <inheritdoc cref="Vector3.Z"/>
    public Fixed Z;

    /// <inheritdoc cref="Vector3.Zero"/>
    public static Vector3Fixed Zero => default;

    /// <inheritdoc cref="Vector3.One"/>
    public static Vector3Fixed One => new(1);

    /// <inheritdoc cref="Vector3.UnitX"/>
    public static Vector3Fixed UnitX => new(1, 0, 0);

    /// <inheritdoc cref="Vector3.UnitY"/>
    public static Vector3Fixed UnitY => new(0, 1, 0);

    /// <inheritdoc cref="Vector3.UnitZ"/>
    public static Vector3Fixed UnitZ => new(0, 0, 1);

    public Fixed this[int index]
    {
        readonly get
        {
            switch (index)
            {
                case 0: return X;
                case 1: return Y;
                case 2: return Z;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }

        set
        {
            switch (index)
            {
                case 0: X = value; break;
                case 1: Y = value; break;
                case 2: Z = value; break;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }
    }

    public Vector3Fixed(Fixed value) : this(value, value, value) {}

    public Vector3Fixed(Fixed x, Fixed y, Fixed z)
    {
        X = x;
        Y = y;
        Z = z;
    }

    // Conversion: Safe - No precision loss possible
    public static implicit operator Vector3Fixed(Vector3Int value)
    {
        return new Vector3Fixed(value.X, value.Y, value.Z);
    }

    // Conversion: Unsafe - Non-deterministic
    // Consider using FromFraction instead
    public static explicit operator Vector3Fixed(Vector3 value)
    {
        return new Vector3Fixed((Fixed)value.X, (Fixed)value.Y, (Fixed)value.Z);
    }

    // Conversion: Loss of fraction
    public static explicit operator Vector3Int(Vector3Fixed value)
    {
        return new Vector3Int((int)value.X, (int)value.Y, (int)value.Z);
    }

    // Conversion: Loss of precision
    public static explicit operator Vector3(Vector3Fixed value)
    {
        return new Vector3((float)value.X, (float)value.Y, (float)value.Z);
    }
}
