// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Numerics;
using System.Runtime.InteropServices;

namespace Exanite.Core.Numerics;

public partial struct Vector2Fixed : IEquatable<Vector2Fixed>, IFormattable
{
    /// <inheritdoc cref="Vector2.X"/>
    public Fixed X;

    /// <inheritdoc cref="Vector2.Y"/>
    public Fixed Y;

    /// <inheritdoc cref="Vector2.Zero"/>
    public static Vector2Fixed Zero => default;

    /// <inheritdoc cref="Vector2.One"/>
    public static Vector2Fixed One => new(1);

    /// <inheritdoc cref="Vector2.UnitX"/>
    public static Vector2Fixed UnitX => new(1, 0);

    /// <inheritdoc cref="Vector2.UnitY"/>
    public static Vector2Fixed UnitY => new(0, 1);

    public Fixed this[int index]
    {
        readonly get
        {
            switch (index)
            {
                case 0: return X;
                case 1: return Y;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }

        set
        {
            switch (index)
            {
                case 0: X = value; break;
                case 1: Y = value; break;
                default: throw new IndexOutOfRangeException(nameof(index));
            }
        }
    }

    public Vector2Fixed(Fixed value) : this(value, value) {}

    public Vector2Fixed(Fixed x, Fixed y)
    {
        X = x;
        Y = y;
    }

    // Conversion: Safe - No precision loss possible
    public static implicit operator Vector2Fixed(Vector2Int value)
    {
        return new Vector2Fixed((Fixed)value.X, (Fixed)value.Y);
    }

    // Conversion: Unsafe - Non-deterministic
    // Consider using Fixed.FromParts or Fixed.FromFraction instead
    public static explicit operator Vector2Fixed(Vector2 value)
    {
        return new Vector2Fixed((Fixed)value.X, (Fixed)value.Y);
    }

    // Conversion: Loss of fraction
    public static explicit operator Vector2Int(Vector2Fixed value)
    {
        return new Vector2Int((int)value.X, (int)value.Y);
    }

    // Conversion: Loss of precision / determinism
    public static explicit operator Vector2(Vector2Fixed value)
    {
        return new Vector2((float)value.X, (float)value.Y);
    }

    public static Vector2Fixed operator *(Vector2Fixed value, Fixed scalar)
    {
        return new Vector2Fixed(value.X * scalar, value.Y * scalar);
    }

    public static Vector2Fixed operator /(Vector2Fixed value, Fixed scalar)
    {
        return new Vector2Fixed(value.X / scalar, value.Y / scalar);
    }

    public static Vector2Fixed operator +(Vector2Fixed left, Vector2Fixed right)
    {
        return new Vector2Fixed(left.X + right.X, left.Y + right.Y);
    }

    public static Vector2Fixed operator -(Vector2Fixed left, Vector2Fixed right)
    {
        return new Vector2Fixed(left.X - right.X, left.Y - right.Y);
    }

    public static Vector2Fixed operator *(Vector2Fixed left, Vector2Fixed right)
    {
        return new Vector2Fixed(left.X * right.X, left.Y * right.Y);
    }

    public static Vector2Fixed operator /(Vector2Fixed left, Vector2Fixed right)
    {
        return new Vector2Fixed(left.X / right.X, left.Y / right.Y);
    }

    public static Vector2Fixed operator %(Vector2Fixed left, Vector2Fixed right)
    {
        return new Vector2Fixed(left.X % right.X, left.Y % right.Y);
    }

    public static Vector2Fixed operator -(Vector2Fixed value)
    {
        return Zero - value;
    }

    public static bool operator ==(Vector2Fixed left, Vector2Fixed right)
    {
        return left.Equals(right);
    }

    public static bool operator !=(Vector2Fixed left, Vector2Fixed right)
    {
        return !left.Equals(right);
    }

    public bool Equals(Vector2Fixed other)
    {
        return X == other.X && Y == other.Y;
    }

    public override bool Equals(object? obj)
    {
        return obj is Vector2Fixed other && Equals(other);
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(X, Y);
    }

    public override string ToString()
    {
        return ToString("G", CultureInfo.CurrentCulture);
    }

    public string ToString([StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format)
    {
        return ToString(format, CultureInfo.CurrentCulture);
    }

    public string ToString([StringSyntax(StringSyntaxAttribute.NumericFormat)] string? format, IFormatProvider? formatProvider)
    {
        string separator = NumberFormatInfo.GetInstance(formatProvider).NumberGroupSeparator;

        return $"<{X.ToString(format, formatProvider)}{separator} {Y.ToString(format, formatProvider)}>";
    }
}
